/*
 * FINBOURNE Scheduler API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.scheduler.model;

import java.util.Objects;
import com.finbourne.scheduler.model.TimeTrigger;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.scheduler.JSON;

/**
 * Holds different kinds of triggers A schedule may only have one type of trigger
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Trigger {
  public static final String SERIALIZED_NAME_TIME_TRIGGER = "timeTrigger";
  @SerializedName(SERIALIZED_NAME_TIME_TRIGGER)
  private TimeTrigger timeTrigger;

  public Trigger() {
  }

  public Trigger timeTrigger(TimeTrigger timeTrigger) {
    
    this.timeTrigger = timeTrigger;
    return this;
  }

   /**
   * Get timeTrigger
   * @return timeTrigger
  **/
  @jakarta.annotation.Nullable
  public TimeTrigger getTimeTrigger() {
    return timeTrigger;
  }


  public void setTimeTrigger(TimeTrigger timeTrigger) {
    this.timeTrigger = timeTrigger;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Trigger trigger = (Trigger) o;
    return Objects.equals(this.timeTrigger, trigger.timeTrigger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeTrigger);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Trigger {\n");
    sb.append("    timeTrigger: ").append(toIndentedString(timeTrigger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("timeTrigger");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Trigger
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Trigger.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Trigger is not found in the empty JSON string", Trigger.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `timeTrigger`
      if (jsonObj.get("timeTrigger") != null && !jsonObj.get("timeTrigger").isJsonNull()) {
        TimeTrigger.validateJsonElement(jsonObj.get("timeTrigger"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Trigger.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Trigger' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Trigger> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Trigger.class));

       return (TypeAdapter<T>) new TypeAdapter<Trigger>() {
           @Override
           public void write(JsonWriter out, Trigger value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Trigger read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Trigger given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Trigger
  * @throws IOException if the JSON string is invalid with respect to Trigger
  */
  public static Trigger fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Trigger.class);
  }

 /**
  * Convert an instance of Trigger to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
